# Create new comment

POST http://localhost:4000/api/comments/75714710-5589-41af-a43c-a181b3b717f2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NmM5NTRkYmJmZDMwMzkzOWNlOTJhYTMiLCJuYW1lIjoiU2FsbHkgU2FuZGVycyIsImlhdCI6MTcyNDQ3NjI3MiwiZXhwIjoxNzI0NDc2NTcyfQ.MKbDkKgzOK4h0erhadvXe6A5FzdpiGSHWgz0ooEnuFE

{
  "text": "Third Test comment"
}

###

# Get all comments of the post
Get http://localhost:4000/api/comments/75714710-5589-41af-a43c-a181b3b717f2?limit=1&page=2

###

#Delete comment

Delete http://localhost:4000/api/comments/5e33aae7-56e8-4639-a497-af3439f8b002
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NmM5NTRkYmJmZDMwMzkzOWNlOTJhYTMiLCJuYW1lIjoiU2FsbHkgU2FuZGVycyIsImlhdCI6MTcyNDQ3NjI3MiwiZXhwIjoxNzI0NDc2NTcyfQ.MKbDkKgzOK4h0erhadvXe6A5FzdpiGSHWgz0ooEnuFE
